### ISSUE TITLE
Host Setup Controls Look Funky When Narrow

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/HubNet-Web#2]
* **Steps to reproduce**: Navigate to `/host` and set your the browser window to be half or less the width of the screen
  * **Expected**: "Launch" button will be full width; text inputs will be vertically aligned; input labels will reside on a single line
  * **Actual**:

![Snip](https://user-images.githubusercontent.com/912890/150460989-3f7bb71f-077a-4b37-b1f4-78a381dc8b27.png)

**Comment by cs2027** [comment]
Done & resolved!
